lies = {
    "2014/6": ["LIE: The mentality of 1200 years of slavery is troubling us."],
    "2014/7": [
        "LIE: Atal Bihari Vajpayee ji inaugurated Jammu and Kashmir rail connections"
    ],
    "2014/8": ["LIE: Kutch has maximum Muslim population of the state"],
    "2014/9": [],
    "2014/10": [
        "LIE: Mahabharata says Karna was not born from his mother’s womb. This means that genetic science was present at that time",
        "LIE: There must have been some plastic surgeon at that time who got an elephant’s head on the body of a human being and began the practice of plastic surgery.",
    ],
    "2014/11": [],
    "2014/12": [],
    "2015/1": [],
    "2015/2": [],
    "2015/3": [],
    "2015/4": [],
    "2015/5": [],
    "2015/6": [],
    "2015/7": [],
    "2015/8": [],
    "2015/9": [],
    "2015/10": [],
    "2015/11": [],
    "2015/12": [],
    "2016/1": [],
    "2016/2": [],
    "2016/3": [],
    "2016/4": [],
    "2016/5": [],
    "2016/6": [],
    "2016/7": [],
    "2016/8": [
        "LIE: The government had completed the work of ‘One Rank, One Pension’ policy for soldiers",
        "LIE: India is the most-preferred destination for foreign direct investments",
    ],
    "2016/9": [],
    "2016/10": [],
    "2016/11": [],
    "2016/12": [
        "The fact that so much of the cash in circulation has been deposited in the banking system indicates the success of this mission (Demonetisation)",
        "LIE: Kisan Credit Cards were launched in 1998, but so far, it was essential to go to a bank, to use them. Now, farmers will have RuPay Debit Cards, which they can use anywhere",
        "LIE: We are introducing a nation-wide scheme for financial assistance to pregnant women. Rs 6,000 will be transferred directly to the bank accounts of pregnant women who undergo institutional delivery and vaccinate their children",
        "LIE: Nations similar to us do not have the amount of currency that we had",
        "LIE: The excess of cash was fuelling … black-marketing… Lack of cash causes difficulty, but excess of cash is even more troublesome…Corruption, black money, and counterfeit notes had become so rampant in India’s social fabric, that even honest people were brought to their knees",
        "LIE: The excess of cash was fuelling inflation",
        "LIE: Government has not changed “even a comma or a full stop” on laws that regulate funding of political parties",
    ],
    "2017/1": [],
    "2017/2": [
        "LIE: Remembering Veer Savarkar on his punya tithi (death anniversary). He was a true patriot who envisioned a strong and developed India",
        "LIE: A conspiracy hatched “across the border” was responsible for a train derailment last November near Kanpur that killed 150 people",
        "LIE: More electricity supplied during Eid than Diwali in U.P",
        "LIE: Maximum number of atrocities against Dalits in U.P",
        "LIE: Congress feels India was born on August 15, 1947. I was surprised yesterday when they said that Jawaharlal Nehru and the Congress gave India democracy. You should know that the Lichhavi clan also had democracy",
        "LIE: Total NPA stood at Rs. 52 lakh crore in March 2014",
        "LIE: Till the time you were in power you lied and said the NPAs were 36% but in 2014 (the year the BJP came to power) we started seeking the truth and looked at the documents. We realised that you gave wrong statistics. NPAs were at 82%.",
        "LIE: Uttar Pradesh is number 1 in crime",
    ],
    "2017/3": [
        "LIE: He (referring to Rahul Gandhi) said he will extract coconut juice in Manipur. Have you ever heard about coconut juice? He will set up ‘aloo ki factory’ in UP"
    ],
    "2017/4": [
        "LIE: From now onwards, women will not have to change their names in the passport after their marriage"
    ],
    "2017/5": [],
    "2017/6": [],
    "2017/7": [],
    "2017/8": [
        "LIE: Then (after demonetization) we found three lakh companies, which were only shell companies",
        "LIE: Around 4.5 lakh people have now come forward and are trying to tread the right path after accepting their mistakes. One lakh people, who had neither heard of Income Tax nor paid Income Tax, have now been forced to do so",
        "LIE: This year, see the results, from 1st April to 5th August more than 56 lakh people filed personal income tax returns. Last year in the same period it was just 22 lakh",
        "LIE: According to the research conducted by outside experts, about Rs 3 lakh crores that had never come into the banking system before, has been brought into the system after the demonetization.",
        "LIE: Today, after three years, I want to tell the countrymen proudly that we have confiscated black money worth Rs.1.25 lakh crores",
        "LIE: Our mothers and sisters are an integral unit of our families. Their contribution in making our future is extremely important. And that is why we have decided to increase the paid maternity leave to 26 weeks from the earlier 12 weeks",
        "LIE: I review government projects every month. A specific project came to my notice. It was a 42-year-old project. Seventy kilometres-72 kilometres of railway lines were to be laid, but the project was lying in limbo for the last 42 years",
        "LIE: Loans worth more than Rs 8 crore have been sanctioned without guarantee to the youth for self-employment",
        "LIE: More than 2 crore poor mothers and sisters are no longer using firewood and using LPG gas stove now",
        "LIE: More than 9 crore farmers have got Soil Health Card",
    ],
    "2017/9": [],
    "2017/10": [
        "LIE: We(BJP) started the Direct Benefit Transfer scheme",
        "LIE: This (Gujarat ro-ro ferry) may be a project between Ghogha and Dahej, but it is a landmark project not only for India but also for entire South East Asia. The ferry service is a first of sorts",
    ],
    "2017/11": [],
    "2017/12": [
        "LIE: Insolvency and Bankruptcy Code (IBC), 2016 has resulted in recovery of Rs. 4 lakh crore out of staggering Rs. 9 lakh crore of NPAs or bad loans given to the corporates under UPA government",
        "LIE: Former PM Vajpayee was a passenger on India’s first ever metro",
        "LIE: ‘PM Modi becomes first passenger of India’s first ever sea plane’ was claimed by Modi’s website",
        "LIE: Sardar Sarovar Dam was inaugurated during Nehru’s time but the congress could not complete it. It was done only after I became the PM",
        "LIE: This is for the first time that the person who is sitting here in Delhi (as the PM) is from Gujarat",
        "LIE: Then Rajasthan CM Ashok Gehlot stopped construction of the Sujalam Sufalam irrigation canal on Mahi river to keep North Gujarat thirsty",
        "LIE: Dr. Manmohan Singh did not do anything about neem-coated urea. The problem was solved after I became the PM",
        "LIE: Former PM Dr Manmohan Singh and former VP Hamid Ansari and former Army Chief General Deepak Kapoor had met Pakistan High Commissioner at Mani Shankar Aiyar’s residence and discussed Gujarat elections.",
        "LIE: Mani Shankar Aiyar compared Congress party to the Mughal dynasty",
    ],
    "2018/1": [
        "LIE: In 2014, after 30 years, the 600 crore voters in India provided complete majority to any political party to form government at the Centre",
        "LIE: Seven million new EPF accounts, doesn’t this show new employment?",
        "LIE: I don’t think earlier anybody experienced the strength of the Indian passport",
    ],
    "2018/2": [
        "LIE: This time in the budget, a standard deduction of Rs. 40,000 was approved by us",
        "LIE: Now that Aadhaar has been implemented and the poor are benefiting, they (Congress) have a problem with its implementation",
        "Govt is committed to the hopes and aspirations of the middle class to bring about ease of living",
        "During Doklam stand-off, Congress people were meeting with Chinese convoy",
        "LIE: The previous governments and their banking policies are responsible for the non-performing asset (NPA) mess",
        "LIE: Had Sardar Vallabhbhai Patel been the first PM of the country, all of Kashmir would have belonged to India today",
        "LIE: The Bidar-Kalburgi rail line was approved by Vajpayee government but from 2004 till 2013, nothing was done. Work only began under the BS Yeddyurappa government",
    ],
    "2018/3": [],
    "2018/4": [
        "LIE: The Ujjwala (Light Up) scheme has transformed the lives, for once and all, of over 3 crore (30 million) women in India’s villages",
        "LIE: We are building about three times more roads than what was being constructed earlier",
        "LIE: In the past one week, over 8.5 lakh toilets have been constructed in Bihar, and that is not an easy task to do",
    ],
    "2018/5": [
        "LIE: In 2015, NDA Government strengthened the SC/ST (Prevention of Atrocities) Act",
        "LIE: Congress humiliated Dr. Ambedkar",
        "LIE: When Shaheed Bhagat Singh, Batukeshwar Dutt, greats like them were jailed fighting for the country’s independence, did any Congress leader go to meet them?",
        "LIE: Women’s safety is not a priority for the state Government",
        "LIE: Under the Congress government, Bengaluru’s infrastructure is crumbling",
        "LIE: ‘We will provide all measures to improve the condition of farmers in India’",
        "LIE: In Sonia Gandhi’s time, LED bulb was sold at Rs 350 and now with BJP in power, it is just Rs 30-40.",
        "LIE: We have constructed toilets for girls in all schools",
        "LIE: Which Congress government, either in Delhi or here in Karnataka ever thought about solving the water problem in Tumakuru",
        "LIE: What has the Congress done in the last 70 years for farmers? The Congress’ neglect of the agriculture sector is very well known",
    ],
    "2018/6": [],
    "2018/7": [
        "LIE: In the ease of getting electricity ranking of World Bank, India has jumped 82 points in last 4 years",
        "LIE: There was an attempt to cover-up the untimely death of freedom-fighter Netaji Subhas Chandra Bose",
        "LIE: Loans were given over the phone in Congress rule, the web of NPAs was spread during this time",
        "LIE: India moved up 42 places in ease of doing business ranking",
        "LIE: Surgical strike was called Jumla strike",
        "LIE: Rafale deal has been carried out with transparency",
        "LIE: Earlier, banks were not open for the poor",
        "LIE: About 2500 Cr has been paid as claims under PMFBY",
        "LIE: More than 6 lakh people now have houses",
    ],
    "2018/8": [
        "LIE: 13 crore MUDRA loans were distributed, boosting entrepreneurship and jobs",
        "LIE: Indian passport is one of the most respected and welcomed in the world",
        "LIE: Women officers, selected through the Short Service Commission, in our defence forces will now have the option to take up permanent commission",
        "LIE: Work on 99 old closed down big irrigation projects is now on-going",
        "LIE: If we had continued at the pace at which electrification was happening in 2013, then it would’ve taken us decades to complete them",
        "LIE: An international organization has released a report which says that in the last 2 years 5 crore people have been lifted out of poverty",
        "LIE: According to a WHO report, deaths of 3 lakh children were prevented due to Swacchta Abhiyan",
        "LIE: Ujjwala Yojana – we have provided gas connections to the poor",
        "LIE: We are moving towards an agricultural export policy so that our farmers can participate with strength in the global market",
        "LIE: Our dream is to double the farmers’ income by 2022, when India completes 75 years of independence",
    ],
    "2018/9": [
        "LIE: Chanakya, Charak, Shushusru, Aryabhatt, Panini, Dhanvantari like scholars are products of Taxashila, Nalanda and Vikramshila Universities",
        "LIE: There are now 100 airports in India out of which 35 were built in the last four years",
    ],
    "2018/10": [
        "LIE: Last govt. made 25 lakh houses but we made 1.25 crore houses in 4 years"
    ],
    "2018/11": [
        "LIE: In four years, Modi has opened an account for every Indian",
        "LIE: We gave approval to 8 medical colleges in Rajasthan",
        "LIE: No roads in rural areas",
        "LIE: For toilets people had to travel long before sunrise, there was no sign of any toilet",
        "LIE: India has shown a big jump in the textile export last year under BJP government",
        "LIE: In 4 years Modi gave gas connections to 90% households",
        "LIE: We have given a strong reply to terrorists",
        "LIE: Congress has come out with their manifesto but have they mentioned that Mobile will be made in Dungarpur?",
        "LIE: Congress did not care about Adivasis",
        "LIE: In the agriculture sector, Madhya Pradesh is no.1 in all of India",
    ],
    "2018/12": [
        "LIE: Congress has promised to farmers but not given anything to Punjab farmers as promised, not even in Karnataka",
        "LIE: In 2013, the number of tourist inflow was 13 lakh",
        "LIE: The government has not received any concerns from the Election Commission on the issue of Electoral Bearer Bonds",
        "LIE: The pricing details have, however, been shared with the Comptroller and Auditor General (hereinafter referred to as CAG), and the report of the CAG has been examined by the Public Accounts Committee… Only a redacted portion …was placed before the Parliament and is in public domain.",
        "LIE: Ayushman Bharat is an excellent example of welfare scheme and use of technology. Within 100 days 4.5 crores have availed this scheme",
        "LIE: Varanasi-Kolkata waterway work initiated",
        "LIE: Only 50% of families had bank accounts. Today, almost all are connected",
        "LIE: Current agrarian crisis due to Congress’s policies",
    ],
    "2019/1": [
        "LIE: Now, culprits are hanged within 3 days, 7days, 11 days & a month. Steps are being taken continuously to get daughters justice & results are evident",
        "LIE: Under the UDAN scheme, 12 lakh seats have been given at lower cost",
        "LIE: Silvassa and Diu are to be smart cities soon. Work is ongoing for this",
        "LIE: Be it land, education or forest produce, my government has done a lot for the tribals",
        "LIE: A special fund of Rs. 7500 crores has been set up under the Blue Revolution scheme under which the fisheries sector will be modernised",
        "LIE: In the last 4 years, our government has removed 7 crore fake accounts from the system, these 7 crore people were those who were never born, they didn’t exist, but they were getting benefit of government facilities",
        "LIE: Today we are on our way to becoming a start- up ecosystem",
        "LIE: Today, India can compete at the international stage. The International Solar alliance is such a stage and through this medium we want to show the world, that ‘One Sun, One World, One Grid’",
        "LIE: At 7.3%, the average GDP growth over the entire term of our Government, has been the highest for any Indian Government since 1991",
        "LIE: CBI is not acceptable to them (Congress) today, tomorrow it will be some other institution. Army, Police, SC, EC, CAG, everyone is wrong except them",
    ],
    "2019/2": [
        "LIE: New Congress government in Rajasthan failed to fulfil promise to waive farm loans in 10 days",
        "LIE: South Korean investment to India has reached 6 billion dollars in 4 years",
        "Lie: In the last 4 years, MSP growth has increased 3 times",
        "LIE: 14,500 houses given to poor people in Yevatmal",
        "LIE: By 2022, every family will have a pucca house",
        "Lie: The whole country is thankful to UP for electing a worthy govt after 30 years, a govt that takes strong decisions. After 30 years of hopelessness, we have brought vikaas",
        "LIE: Congress party always used the unorganised sector as a vote bank but never did anything for their benefit. For the first time, a law for unorganised sector has been made under PM Shram Yogi Mandhan Yojana",
    ],
    "2019/3": [
        "LIE: PM Shram Yogi Man Dhan Yojana has been introduced to assist workers in the unorganised sectors like tea gardens",
        "LIE: We are fully committed towards uplifting the tea garden workers and our govt has given them several benefits",
        "LIE: This (PM-KISAN) has also ensured direct support to 82 lakh farmers ‘ bank accounts in Andhra Pradesh",
        "LIE: Who approved the first Indian Institute of Petroleum (IIP) for Andhra Pradesh? Your chaukidar. Who approved the first Greenfield petrochemical complex for Andhra Pradesh?",
        "LIE: Who approved the first National Institute of Ocean Technology (NIOT) for Andhra Pradesh? Modi",
        "LIE: Previously sugarcane farmers had to wait 1-2 years to get their dues after selling off their produce but under the BJP government, they have been getting it the same year",
        "LIE: Our scientists were demanding for testing of shooting down of satellite in space, the then government (UPA) postponed this decision also",
        "LIE: Did women feel safe under previous governments? Did they do anything to ensure better safety for you? But now, you would have noticed and felt the change ever since the Yogi Adityanath government came to power. The criminals are scared to roam freely",
        "LIE: For the first time, a record number of homes were electrified by the Modi govt",
        "LIE: For 40 years, our soldiers had been asking for OROP, this chowkidar came and fulfilled their demands",
    ],
    "2019/4": [
        "LIE: In 2019, they (Congress) have the record of contesting the lowest number of seats in their entire political history",
        "LIE: All departments should have enough freedom to even raid my house. I will never interfere in their work",
        "LIE: There is no discussion on price rise. Even the opposition has not raised it",
        "LIE: Those who claim there were job losses due to demonetisation don’t have statistics to back it",
        "LIE: The focus is to make 80% of production in India by strengthening our public sector. We want technology transfer in all our defence deals",
        "LIE: I used to wash my own clothes until I became a CM",
        "LIE: Unlike the previous govt, we don’t keep complaining about lack of funds. (in reference to the Army)",
        "LIE: In J&K, we waited for a govt to form and kept the assembly in suspension. Only when no one came forward, we formed govt",
        "LIE: Safety and security of every section of the society is the responsibility of every govt and we have been doing that in the last 5 years",
        "LIE: 17 crore Mudra loans have been given in the last four years out of which 4.25 crore loans were given to first-time entrepreneurs. This clearly shows that over 4 crore entrepreneurs started their business",
    ],
    "2019/5": [
        "LIE: None of my programs were cancelled",
        "LIE: Since the Chowkidar has come to power has it (bomb blasts) stopped or not?",
        "LIE: Those opposing surgical strikes are opposing the martyrs",
        "LIE: Everyone saw the ‘goondaism’ by TMC",
        "LIE: Recently a dalit girl was raped in Rajasthan & the Congress tried to cover it up",
        "LIE: The opposition will resort to spreading fake news, allegations, abuses etc. because they cannot fight on issues against Modi. For them, the main issue is Modi",
        "LIE: 130 crore Indians have supported me",
        "LIE: Rahul, Sonia Gandhi or anyone from Congress has never expressed any regret for 1984 riots",
        "LIE: I used email to transmit a photograph in 1987-88",
        "Lie: They (Congress) were supposed to waive off farm loans in MP, instead police are going to arrest farmers",
    ],
    "2019/6": [],
    "2019/7": [],
    "2019/8": [
        "LIE: Article 370 was a hurdle for the development of Kashmir",
        "LIE: The dream of Dr. Baba Saheb Ambedkar, Dr. Shyama Prasad Mukherjee, Atal Bihari Vajpayee and millions of people have now come true",
    ],
    "2019/9": [],
    "2019/10": [],
    "2019/11": [],
    "2019/12": [
        "LIE: Rumors of detention-centers being spread by Urban Naxals and Congress",
        "LIE: A lot of lies are being spread about NRC as well. We did not make it, nor did we bring it to the Parliament or announce it",
        "LIE: NRC was made during the Congress regime",
        "LIE: The 130 crore Indians have no connection to the CAB",
        "Lie: In the last few years, the speed of influx of FDI in India has increased. FDI, for me, has two meanings. For me, FDI is, ‘First Develop India’",
    ],
    "2020/1": [
        "Lie: Not only J&K, but the entire country is witnessing a new dawn of peace",
        "Lie: Our North East is our pride. Their culture, traditions and demography remains untouched by this Amendment (CAA 2019). The Central Govt has taken care of it specifically",
        "Lie: Post Independence, all leaders including Mahatma Gandhi had said that India should give citizenship to the people who’re being religiously persecuted in Pakistan",
        "Lie: With your help, India has announced itself open-defecation free on the 150th birth anniversary of Mahatma Gandhi Ji",
    ],
    "2020/2": [
        "LIE: Who stopped them (Congress) from implementing the Constitution of India in Jammu and Kashmir?",
        "LIE: Omar Abdullah had said that the abrogation of Article 370 would bring a massive earthquake and will divide Kashmir from India",
        "LIE: Such a big secular person like Nehru … why did he not use then all citizens instead of minorities there?",
        "LIE: We’ve worked on electricity, rail, airports, mobile connectivity and other such facilities",
    ],
    "2020/3": [],
    "2020/4": [],
    "2020/5": [],
    "2020/6": [],
    "2020/7": [
        "Lie: India much better placed than other countries in fight against Covid-19",
        "LIE: Today, Rewa has really created history. The name of Asia’s largest solar power project has now been associated with it.",
    ],
    "2020/8": [],
    "2020/9": [],
    "2020/10": [],
}

